services:
  - type: web
    name: shakthi-yoga-frontend
    runtime: node
    plan: free
    repo: https://github.com/ragul835/shakthi-yoga-frontend
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://shakthi-yoga-backend.onrender.com/api